name: Latency Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor: # Přejmenováno pro srozumitelnost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run latency test
        run: php scripts/test_latency.php

      # TOTO JE NOVÝ KROK MÍSTO DEPLOYE
      - name: Commit and push latency logs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📈 Update latency logs"
          # Ujisti se, že cesty odpovídají tomu, kam skript ukládá soubory
          file_pattern: "latency_logs/*.csv index.html"
          github_token: ${{ secrets.K_TOKEN }}